### ISSUE TITLE
"version" attribute

### ISSUE THREAD

**Issue by permyakovsv** [opscode-cookbooks/php#93]
Please add "version" attribute, in package resource

**Comment by Rockstar04** [comment]
This seems redundant currently, for Windows since you can specify the windows MSI name and source (to determine veriosn installed), and for Linux since the name of the package to install can be set as well.

If you need a version not suppored by the packages on a given linux platform, you will need to use a PPA (currently ouside the scope of this cookbook), or build from source (which is supported)
